twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        locales: '%app.locales%'
    form_theme:
        - '@FOSCKEditor/form/ckeditor_widget.html.twig'
